# -*- coding: utf-8 -*-
"""Final 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF0HI4afGH3E4zUh9ULInOA8xy6rASco
"""

#โปรแกรมคำนวณอายุจากปีเกิด 1

#Input
CYear = int(input(" ปีปัจจุบัน:  "))
BYear = int(input(" ปีปัจจุเกิด:  "))

#Process
Age = (CYear - BYear)

#Output
print (f"อายุของคุณคือ " + Age + " ปี")