# -*- coding: utf-8 -*-
"""Final 10 ver. 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnGcTCeta_pSnEOpn-kAigYVm3AlX2Pa
"""

#โปรแกรมคำนวณอายุจากปีเกิด 2 (A.I)

#Input
CYear = int(input(" ปีปัจจุบัน:  "))
BYear = int(input(" ปีปัจจุเกิด:  "))

#Process
Age = (CYear - BYear)

#Output
print(f"อายุของคุณคือ {Age} ปี")

